#!/bin/sh
#
# Copyright (C) 2015 Yen-Chine, Lee <coldnew.tw@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Update grub for dual boot osx
# We mount this device at /boot/efi, the directory structure like following
#
# .
# ├── mach_kernel
# └── System
#     └── Library
#         └── CoreServices
#             ├── boot.efi
#             └── SystemVersion.plist
#
# 4 directories, 2 files
#

# Variables
BOOT=/boot/efi
BOOT_EFI=${BOOT}/System/Library/CoreServices/boot.efi
GRUB_CFG=/boot/grub/grub.cfg

# Before we start, check the /boot/efi structure is ok for macbook firmware to
# boot.
#
if [ ! -d ${BOOT} ]; then
    echo "ERROR: $BOOT structure is valid"
    exit -1
fi

# TODO: Add more secure check
grub2-mkconfig -o /boot/grub/grub.cfg

grub2-mkstandalone \
    -d /usr/lib/grub/x86_64-efi \
    -O x86_64-efi \
    -o ${BOOT_EFI} ${GRUB_CFG}
