#!/bin/sh

start() {
    # Fix osx keyboard layout, if this not set, the key pair "`~" will
    # becomes "<>"
    echo 0 > /sys/module/hid_apple/parameters/iso_layout
}

stop() {
    :
}

case $1 in
  start|stop) "$1" ;;
esac
