
* Underdevelopment

Since MacBook Pro Retina 2015 =(Macbook Pro 12,1)= is a brand new device, some function may not work
propely, I still try to make everything work under Gentoo Linux, the patch will
be apply to [[https://github.com/coldnew/coldnew-overlay][coldnew-overlay]] since it's my own overlay.

Why we don't has any overlay like macbook-overlay ?

Following are some function I want to work but cant use right now, if marked
with =X=, which means it's work.

- [X] wifi

  I have following error when launch wl.ko (broadcom-sta)

  #+BEGIN_EXAMPLE
  [   12.446547] wl driver 6.30.223.248 (r487574) failed with code 1
  [   12.447551] [wl_cfg80211_detach()] in ndev=ffff88045bb34000: IEEE80211ptr=          (null)
  #+END_EXAMPLE

  The official =broadcom-sta-6.30.223.248-r3= driver seams like not support =BCM43602= which used in MBPR 12,1,
  we should use a kernel provide driver =brcfmac=.

  Use =brcmfmac= driver shipped with linux kernel can let wifi work, you also need to install =sys-kernel/linux-firmware= for =/lib/firmware/brcm/brcmfmac43602-pcie.bin=.

  I use =/etc/portage/savedconfig/sys-kernel/linux-firmware= to control which firmware I need to install, and the firmware we need to make wifi work is

  : brcm/brcmfmac43602-pcie.bin

  Add the savedconfig file and enable =savedconfig= USE to emerge linux-firmware

  : USE="savedconfig" emerge sys-kernel/linux-firmware

- [X] keyboard fn keys

  apply following patch: https://gist.github.com/tmacedo/016a3d0fae9e3d87a1dd

- [ ] wayland

  No... has anyone success on it ?

- [ ] trackpad

  Forcetouch trackpad can do BTN_TOUCH, but two finger scrolling has problem.

- [ ] suspend

  Untest yet, I more prefer =suspend to RAM= instead of =hibernate to SSD=

* Macbook Pro Retina 2015 configs

This my config files or scripts for Gentoo Linux on Macbook Pro Retina 2015 13".

Fell free to use it :)

Note: currently there's no any =macbook-overlay= for Gentoo Linux, I use my [[https://github.com/coldnew/coldnew-overlay][coldnew-overlay]] instead.

* Systemd Script

- my-stuff.service

  This service start something I want to start when system start.

* Other files info

- local-service

  This file will install to =/usr/share/macbookair-2013/= , which is
  used for =my-stuff.service= systemd script.

- kernel-config.example

  My kernel-config for Macbook Air 2013, note that this config just
  install to =/usr/share/macbookair-2013/=.

- fstab.example

  My /etc/fstab

- boot-update

  A simple update grub script for dual boot on Macbook Air
